#!/bin/bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────────
# update.sh — upgrade the AI CLI stack to the latest releases, safely.
#
#   1. Check the currently-installed Claude Code version.
#   2. Snapshot config into backup/YYYYMMDD_HHMMSS/ with a generated
#      rollback.sh, so any upgrade can be reverted.
#   3. Upgrade Claude Code to latest (native `claude update`, or npm
#      if that's how it was installed).
#   4. Upgrade the sibling agent CLIs when present — codex,
#      cursor-agent, cortex, opencode, gemini, pi, grok, headroom
#      (scripts/agents-update.sh, the same script ansible-ai/update.yml
#      runs on the fleet; also reports 9router gateway status).
#   5. Re-vendor the 9router skills from upstream and deploy them to
#      ~/.claude/skills (scripts/vendor-9router-skills.sh --deploy).
#   6. Prune old backups (last 7 days + first-of-month snapshots).
#   7. With --all: propagate to the fleet servers via
#      ansible-ai/update.yml --limit aorus_ai (this machine was already
#      updated by steps 1-6, so the playbook skips it).
#
# Flags:
#   --all          After the local update, run the fleet playbook so every
#                  server gets the same treatment. Requires ansible + an
#                  inventory (ansible-ai/inventory.local.yml). Note: servers
#                  pull from origin/main — use ./deploy.sh to publish config
#                  changes first.
#   --dry-run      Take the backup, but DON'T upgrade. Previews the Claude
#                  step only — sibling CLIs, 9router skills, prune, and
#                  fleet are all skipped.
#   --claude-only  Skip the sibling agent CLIs and 9router skills (4-5).
#   --no-prune     Skip the post-upgrade backup prune.
# ─────────────────────────────────────────────────────────────────

# ── Colors & helpers ─────────────────────────────────────────────
BOLD='\033[1m'; DIM='\033[2m'; GREEN='\033[32m'; YELLOW='\033[33m'
RED='\033[31m'; CYAN='\033[36m'; RESET='\033[0m'
ok()     { echo -e "  ${GREEN}✓${RESET} $1"; }
skip()   { echo -e "  ${DIM}○ $1${RESET}"; }
warn()   { echo -e "  ${YELLOW}!${RESET} $1"; }
fail()   { echo -e "  ${RED}✗${RESET} $1"; }
header() { echo -e "\n${BOLD}$1${RESET}"; }

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"
CLAUDE_DIR="$HOME/.claude"
CLAUDE_JSON="$HOME/.claude.json"
BACKUP_ROOT="$DOTFILES_DIR/backup"
TS="$(date +%Y%m%d_%H%M%S)"

DRY_RUN="no"; RUN_PRUNE="yes"; RUN_AGENTS="yes"; RUN_FLEET="no"
for arg in "$@"; do
  case "$arg" in
    --all)         RUN_FLEET="yes" ;;
    --dry-run)     DRY_RUN="yes" ;;
    --claude-only) RUN_AGENTS="no" ;;
    --no-prune)    RUN_PRUNE="no" ;;
    -h|--help)
      echo "Usage: ./update.sh [--all] [--dry-run] [--claude-only] [--no-prune]"
      echo "  Backs up config to backup/<timestamp>/ then upgrades Claude Code"
      echo "  and the sibling agent CLIs (codex, cursor-agent, cortex, opencode, gemini, pi, grok, headroom)."
      echo "  --all also runs ansible-ai/update.yml against the fleet servers afterward."
      exit 0 ;;
    *) warn "Unknown flag: $arg (ignored)" ;;
  esac
done

SUDO=""
[ "$(id -u)" -ne 0 ] && command -v sudo &>/dev/null && SUDO="sudo"

# ── Locate Claude Code & determine how it was installed ──────────
if ! command -v claude &>/dev/null; then
  fail "Claude Code isn't installed. Run ./setup.sh first."
  exit 1
fi

CLAUDE_BIN="$(command -v claude)"
CURRENT_VERSION="$(claude --version 2>/dev/null | awk '{print $1}')"

INSTALL_METHOD="native"
CLAUDE_BIN_TARGET=""
if npm ls -g @anthropic-ai/claude-code &>/dev/null; then
  INSTALL_METHOD="npm"
elif [ -L "$CLAUDE_BIN" ]; then
  CLAUDE_BIN_TARGET="$(readlink -f "$CLAUDE_BIN" 2>/dev/null || true)"
fi

header "Claude Code Update"
ok "Installed version: ${CURRENT_VERSION:-unknown}"
ok "Install method:    $INSTALL_METHOD${CLAUDE_BIN_TARGET:+  (→ $CLAUDE_BIN_TARGET)}"

# ── 1. Backup ────────────────────────────────────────────────────
BACKUP_DIR="$BACKUP_ROOT/$TS"
CFG_DIR="$BACKUP_DIR/claude-config"
mkdir -p "$CFG_DIR"

# Copy the config that an upgrade could migrate/break. -L dereferences
# symlinks so the backup holds real files (e.g. a symlinked settings.json).
copy_if_present() {
  local src="$1" dst="$2"
  [ -e "$src" ] || return 0
  cp -L "$src" "$dst" 2>/dev/null && return 0
  cp "$src" "$dst" 2>/dev/null || true
}
copy_if_present "$CLAUDE_DIR/settings.json"       "$CFG_DIR/settings.json"
copy_if_present "$CLAUDE_DIR/settings.local.json" "$CFG_DIR/settings.local.json"
copy_if_present "$CLAUDE_DIR/CLAUDE.md"           "$CFG_DIR/CLAUDE.md"
copy_if_present "$CLAUDE_JSON"                     "$CFG_DIR/claude.json"

HAS_SETTINGS_LOCAL="no"; [ -f "$CFG_DIR/settings.local.json" ] && HAS_SETTINGS_LOCAL="yes"

# Machine-readable manifest that rollback.sh sources.
cat > "$BACKUP_DIR/manifest.env" <<EOF
# Auto-generated by update.sh — do not edit.
CLAUDE_VERSION_BEFORE="${CURRENT_VERSION}"
INSTALL_METHOD="${INSTALL_METHOD}"
CLAUDE_BIN="${CLAUDE_BIN}"
CLAUDE_BIN_TARGET="${CLAUDE_BIN_TARGET}"
DEST_SETTINGS="${CLAUDE_DIR}/settings.json"
DEST_SETTINGS_LOCAL="${CLAUDE_DIR}/settings.local.json"
HAS_SETTINGS_LOCAL="${HAS_SETTINGS_LOCAL}"
DEST_CLAUDE_MD="${CLAUDE_DIR}/CLAUDE.md"
DEST_CLAUDE_JSON="${CLAUDE_JSON}"
EOF

# Static rollback script — reads manifest.env for the concrete paths.
cat > "$BACKUP_DIR/rollback.sh" <<'ROLLBACK'
#!/bin/bash
# Restore the config snapshot in this folder and revert Claude Code to the
# version that was installed before the corresponding update.sh run.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
. "$HERE/manifest.env"
cfg="$HERE/claude-config"

echo "Rolling back Claude Code to ${CLAUDE_VERSION_BEFORE:-previous}..."

[ -f "$cfg/settings.json" ]       && cp "$cfg/settings.json"       "$DEST_SETTINGS"       && echo "  restored settings.json"
[ "$HAS_SETTINGS_LOCAL" = "yes" ] && cp "$cfg/settings.local.json" "$DEST_SETTINGS_LOCAL" && echo "  restored settings.local.json"
[ -f "$cfg/CLAUDE.md" ]           && cp "$cfg/CLAUDE.md"           "$DEST_CLAUDE_MD"       && echo "  restored CLAUDE.md"
[ -f "$cfg/claude.json" ]         && cp "$cfg/claude.json"         "$DEST_CLAUDE_JSON"     && echo "  restored ~/.claude.json"

if [ "$INSTALL_METHOD" = "native" ] && [ -n "$CLAUDE_BIN_TARGET" ] && [ -e "$CLAUDE_BIN_TARGET" ]; then
  ln -sfn "$CLAUDE_BIN_TARGET" "$CLAUDE_BIN"
  echo "  re-pointed claude -> $CLAUDE_BIN_TARGET"
elif [ "$INSTALL_METHOD" = "native" ]; then
  echo "  ! previous binary ($CLAUDE_BIN_TARGET) is gone — reinstall with:"
  echo "      claude install ${CLAUDE_VERSION_BEFORE}"
else
  echo "  npm install: revert with:"
  echo "      npm install -g @anthropic-ai/claude-code@${CLAUDE_VERSION_BEFORE}"
fi

echo "Rollback complete. Restart Claude Code."
ROLLBACK
chmod +x "$BACKUP_DIR/rollback.sh"

ok "Backup: backup/$TS/  ${DIM}(config + rollback.sh)${RESET}"

# ── 2. Upgrade ───────────────────────────────────────────────────
if [ "$DRY_RUN" = "yes" ]; then
  header "Dry run"
  if [ "$INSTALL_METHOD" = "npm" ]; then
    skip "Would run: ${SUDO:+sudo }npm install -g @anthropic-ai/claude-code@latest"
  else
    skip "Would run: claude update"
  fi
  [ "$RUN_FLEET" = "yes" ] && skip "Would run: ansible-playbook update.yml --limit aorus_ai  (fleet servers)"
  ok "Backup created; no upgrade performed."
  exit 0
fi

header "Upgrading"
if [ "$INSTALL_METHOD" = "npm" ]; then
  npm install -g @anthropic-ai/claude-code@latest \
    || $SUDO npm install -g @anthropic-ai/claude-code@latest \
    || { fail "npm upgrade failed"; exit 1; }
else
  claude update || { fail "claude update failed"; exit 1; }
fi

NEW_VERSION="$(claude --version 2>/dev/null | awk '{print $1}')"

if [ "$NEW_VERSION" = "$CURRENT_VERSION" ]; then
  ok "Already on the latest version (${NEW_VERSION})."
else
  ok "Upgraded: ${CURRENT_VERSION} → ${GREEN}${NEW_VERSION}${RESET}"
  echo -e "  ${DIM}Restart Claude Code to load the new version.${RESET}"
fi
echo -e "  ${DIM}Roll back anytime:  ${CYAN}backup/$TS/rollback.sh${RESET}"

# ── 3. Sibling agent CLIs ────────────────────────────────────────
if [ "$RUN_AGENTS" = "yes" ] && [ -x "$DOTFILES_DIR/scripts/agents-update.sh" ]; then
  echo
  "$DOTFILES_DIR/scripts/agents-update.sh" || warn "Some agent CLI upgrades failed (non-fatal)."
fi

# ── 3b. herdr (firstmate session backend, macOS/brew only) ───────
# Local-only by design: this lives in update.sh (control-node orchestrator),
# NOT agents-update.sh — so the ansible fleet never upgrades it. The Mac
# control nodes that run firstmate keep it current; the Linux aorus hosts
# never see it. brew-gated, so it also no-ops on a non-brew mac.
if [ "$RUN_AGENTS" = "yes" ] && command -v brew &>/dev/null && command -v herdr &>/dev/null; then
  header "herdr (firstmate backend)"
  before_herdr="$(herdr --version 2>/dev/null | awk '{print $NF}')"
  if brew upgrade herdr >/dev/null 2>&1; then
    after_herdr="$(herdr --version 2>/dev/null | awk '{print $NF}')"
    [ "$before_herdr" = "$after_herdr" ] && ok "herdr: already latest (${after_herdr})" \
      || ok "herdr: ${before_herdr} → ${after_herdr}"
  else
    ok "herdr: already latest (${before_herdr})"
  fi
fi

# ── 3c. herdr-file-viewer content renderers (bat / delta / glow) ──
# Cross-platform, unlike herdr above: these are useful on any host and the
# fleet's Linux boxes can carry them too. INSTALLS what's missing rather than
# only upgrading, so an existing checkout picks them up without a full
# setup.sh re-run. Per-OS naming differs — Debian ships bat's binary as
# `batcat` (bacula-console clash) and has no glow at all; setup.sh owns the
# Charm-repo + shim work, so here a missing glow on apt is just reported.
if [ "$RUN_AGENTS" = "yes" ]; then
  hr_missing=""
  if command -v brew &>/dev/null; then
    header "herdr-file-viewer renderers"
    for hr_pair in bat:bat git-delta:delta glow:glow; do
      command -v "${hr_pair#*:}" &>/dev/null || hr_missing="$hr_missing ${hr_pair%%:*}"
    done
    if [ -n "$hr_missing" ]; then
      # shellcheck disable=SC2086
      brew install $hr_missing >/dev/null 2>&1 \
        && ok "renderers installed —${hr_missing}" \
        || warn "renderer install failed — brew install${hr_missing} (non-fatal)"
    else
      brew upgrade bat git-delta glow >/dev/null 2>&1 || true
      ok "renderers current (bat, delta, glow)"
    fi
  elif command -v apt-get &>/dev/null; then
    header "herdr-file-viewer renderers"
    command -v batcat &>/dev/null || command -v bat &>/dev/null || hr_missing="$hr_missing bat"
    command -v delta &>/dev/null || hr_missing="$hr_missing git-delta"
    command -v glow &>/dev/null || warn "glow absent — run setup.sh to add Charm's apt repo"
    if [ -n "$hr_missing" ]; then
      $SUDO apt-get update -y >/dev/null 2>&1 || true
      # shellcheck disable=SC2086
      $SUDO apt-get install -y $hr_missing >/dev/null 2>&1 \
        && ok "renderers installed —${hr_missing}" \
        || warn "renderer install failed — apt-get install${hr_missing} (non-fatal)"
    else
      ok "renderers current (bat/batcat, delta)"
    fi
  fi
fi

# ── 3d. Spec & issue tooling (openspec, bd) ──────────────────────
# The OpenSpec + Beads pair backing the spec → task-DAG workflow. Cross-platform
# npm globals, so unlike herdr above this runs on the fleet too. setup.sh owns
# first install; this only upgrades what is already present. Versions come from
# npm's own metadata rather than each CLI's version flag, so one code path
# covers both packages.
#
# Beads deliberately stops at the binary. On a remote-backed Dolt database an
# upgrade can cross a schema migration, where the correct sequence is per-clone
# and per-project: sync, `bd export --all`, upgrade, then exactly one designated
# clone runs `bd migrate && bd dolt push` while the rest run `bd bootstrap`.
# update.sh runs machine-wide and cannot know which checkouts are remote-backed
# or which clone is designated, so it reports the bump and points at the guide
# rather than guessing. See references/openspec-beads-plan.md.
if [ "$RUN_AGENTS" = "yes" ] && command -v npm &>/dev/null && command -v jq &>/dev/null; then
  st_version() {   # <pkg> — installed global version, empty if absent
    npm ls -g --depth=0 --json 2>/dev/null \
      | jq -r --arg p "$1" '.dependencies[$p].version // empty'
  }
  st_shown="no"
  for st_entry in "@fission-ai/openspec:openspec:OpenSpec" "@beads/bd:bd:Beads"; do
    st_pkg="${st_entry%%:*}"; st_rest="${st_entry#*:}"
    st_bin="${st_rest%%:*}"; st_label="${st_rest#*:}"
    command -v "$st_bin" &>/dev/null || continue
    [ "$st_shown" = "yes" ] || { header "Spec & issue tooling"; st_shown="yes"; }
    if [ "$DRY_RUN" = "yes" ]; then
      skip "Would run: ${SUDO:+sudo }npm install -g ${st_pkg}@latest"
      continue
    fi
    st_before="$(st_version "$st_pkg")"; st_before="${st_before:-unknown}"
    if ! npm install -g "${st_pkg}@latest" >/dev/null 2>&1 \
      && ! $SUDO npm install -g "${st_pkg}@latest" >/dev/null 2>&1; then
      warn "${st_label}: upgrade failed — npm install -g ${st_pkg}@latest (non-fatal)"
      continue
    fi
    st_after="$(st_version "$st_pkg")"; st_after="${st_after:-unknown}"
    if [ "$st_before" = "$st_after" ]; then
      ok "${st_label}: already latest (${st_after})"
    else
      ok "${st_label}: ${st_before} → ${st_after}"
      if [ "$st_bin" = "bd" ]; then
        warn "bd version moved — this may cross a Dolt schema migration."
        warn "  Per project with a remote-backed DB: bd info --whats-new; bd hooks install"
        warn "  Upgrade guide: https://beads.gascity.com/getting-started/upgrading"
      fi
    fi
  done
fi

# ── 3e. Repo tooling (fzf, shellcheck) ───────────────────────────
# bin/herdr-new-project dies without fzf, and `just lint` aborts when the
# linter itself is absent. Like the renderers above, this INSTALLS what is
# missing rather than only upgrading, so an existing checkout picks them up
# without a full setup.sh re-run. Same package name on brew and apt.
if [ "$RUN_AGENTS" = "yes" ]; then
  # Recomputed after installing so success is judged on what landed on PATH,
  # not on brew's/apt's exit code — both exit 0 on no-ops that install nothing.
  rt_scan() {
    rt_missing=""
    for rt_tool in fzf shellcheck; do
      command -v "$rt_tool" &>/dev/null || rt_missing="$rt_missing $rt_tool"
    done
  }
  rt_scan
  if command -v brew &>/dev/null; then
    header "Repo tooling"
    if [ "$DRY_RUN" = "yes" ]; then
      [ -n "$rt_missing" ] && skip "Would run: brew install${rt_missing}" \
        || skip "Would run: brew upgrade fzf shellcheck"
    elif [ -n "$rt_missing" ]; then
      # shellcheck disable=SC2086
      brew install $rt_missing >/dev/null 2>&1 || true
      rt_scan
      [ -z "$rt_missing" ] && ok "repo tooling installed (fzf, shellcheck)" \
        || warn "still missing —${rt_missing} (brew install${rt_missing})"
    else
      brew upgrade fzf shellcheck >/dev/null 2>&1 || true
      ok "repo tooling current (fzf, shellcheck)"
    fi
  elif command -v apt-get &>/dev/null; then
    header "Repo tooling"
    if [ "$DRY_RUN" = "yes" ]; then
      [ -n "$rt_missing" ] && skip "Would run: apt-get install${rt_missing}" \
        || skip "repo tooling current (fzf, shellcheck)"
    elif [ -n "$rt_missing" ]; then
      $SUDO apt-get update -y >/dev/null 2>&1 || true
      # shellcheck disable=SC2086
      $SUDO apt-get install -y $rt_missing >/dev/null 2>&1 || true
      rt_scan
      [ -z "$rt_missing" ] && ok "repo tooling installed (fzf, shellcheck)" \
        || warn "still missing —${rt_missing} (apt-get install${rt_missing})"
    else
      ok "repo tooling current (fzf, shellcheck)"
    fi
  fi
fi

# ── 3f. cass (coding-agent session search) ───────────────────────
# Upgrades only what setup.sh already installed — a host without cass is left
# alone rather than silently gaining a tool mid-update. Two paths, because the
# Linux fleet has no Homebrew: brew upgrade on macOS, the upstream installer
# (prebuilt release asset, --verify checks the published sha256) elsewhere.
#
# The skill is re-fetched from upstream every run rather than versioned here.
# cass is MIT with a rider forbidding making it or derivative works available
# to OpenAI/Anthropic and this repo is public, so the file belongs on the host
# and not in git. See references/cass.md.
if [ "$RUN_AGENTS" = "yes" ] && command -v cass &>/dev/null; then
  header "cass (session search)"
  cs_before="$(cass --version 2>/dev/null | head -1)"
  if [ "$DRY_RUN" = "yes" ]; then
    skip "Would upgrade cass (currently ${cs_before:-unknown})"
  else
    if command -v brew &>/dev/null; then
      brew upgrade dicklesworthstone/tap/cass >/dev/null 2>&1 || true
    else
      curl -fsSL "https://raw.githubusercontent.com/Dicklesworthstone/coding_agent_session_search/main/install.sh" \
        | bash -s -- --easy-mode --verify >/dev/null 2>&1 || true
    fi
    cs_after="$(cass --version 2>/dev/null | head -1)"
    [ "$cs_before" = "$cs_after" ] \
      && ok "cass: already latest (${cs_after:-unknown})" \
      || ok "cass: ${cs_before:-unknown} → ${cs_after:-unknown}"

    # Refresh the agent-facing skill; keep the existing copy if upstream is down.
    mkdir -p "$HOME/.claude/skills/cass"
    if curl -fsSL --max-time 20 \
      "https://raw.githubusercontent.com/Dicklesworthstone/coding_agent_session_search/main/SKILL.md" \
      -o "$HOME/.claude/skills/cass/SKILL.md.tmp" 2>/dev/null \
      && [ -s "$HOME/.claude/skills/cass/SKILL.md.tmp" ]; then
      mv "$HOME/.claude/skills/cass/SKILL.md.tmp" "$HOME/.claude/skills/cass/SKILL.md"
      ok "cass skill refreshed"
    else
      rm -f "$HOME/.claude/skills/cass/SKILL.md.tmp"
      warn "cass skill fetch failed — keeping the existing copy (non-fatal)"
    fi
  fi
fi

# ── 4. 9router skills (vendored from decolua/9router) ────────────
# Re-vendors the skill set from upstream and deploys it to
# ~/.claude/skills. Writes into the repo's skills/ dir, so changes
# still need a commit + push before the fleet sees them.
if [ "$RUN_AGENTS" = "yes" ] && [ -x "$DOTFILES_DIR/scripts/vendor-9router-skills.sh" ]; then
  header "9router skills"
  if ! command -v gh &>/dev/null; then
    skip "gh CLI not available — skills not re-vendored"
  elif "$DOTFILES_DIR/scripts/vendor-9router-skills.sh" --deploy >/dev/null 2>&1; then
    if git -C "$DOTFILES_DIR" status --porcelain -- skills/9router\* 2>/dev/null | grep -q .; then
      ok "Re-vendored from decolua/9router → ~/.claude/skills"
      warn "skills/ has uncommitted changes — commit + push so the fleet picks them up"
    else
      ok "Already current (deployed to ~/.claude/skills)"
    fi
  else
    warn "9router skills re-vendor failed (non-fatal — check gh auth / network)"
  fi
fi

# ── 5. Prune old backups ─────────────────────────────────────────
if [ "$RUN_PRUNE" = "yes" ] && [ -x "$DOTFILES_DIR/scripts/backup-prune.sh" ]; then
  echo
  "$DOTFILES_DIR/scripts/backup-prune.sh" || warn "Backup prune had issues (non-fatal)."
fi

# ── 6. Fleet propagation (--all) ─────────────────────────────────
# Servers only (--limit aorus_ai): this machine was already updated above,
# and update.yml's local play would redo the same work. Servers pull the
# repo from origin/main — publish config changes with ./deploy.sh first.
if [ "$RUN_FLEET" = "yes" ]; then
  header "Fleet update (ansible-ai/update.yml --limit aorus_ai)"
  INV="$DOTFILES_DIR/ansible-ai/inventory.local.yml"
  if ! command -v ansible-playbook &>/dev/null; then
    fail "ansible-playbook not found — install ansible, or run this from the control node."
    exit 1
  elif [ ! -f "$INV" ]; then
    fail "No inventory at ansible-ai/inventory.local.yml"
    echo -e "  ${DIM}Bootstrap it:  cp ansible-ai/inventory.example.yml ansible-ai/inventory.local.yml${RESET}"
    exit 1
  fi
  if (cd "$DOTFILES_DIR/ansible-ai" && ansible-playbook update.yml --limit aorus_ai); then
    ok "Fleet servers updated."
  else
    warn "Fleet update finished with failures — offline hosts are skipped; check the recap above."
  fi
fi

# ── Verify the upgraded environment ──────────────────────────────
# update.sh upgrades CLIs and re-vendors skills — the operations most likely
# to break an asset — so verify immediately afterwards. Read-only, and never
# fails the update: an upgrade is not broken because an unrelated MCP server
# is down, and conflating the two teaches you to ignore the exit code.
header "Verifying assets"
if [ -x "$DOTFILES_DIR/scripts/preflight.sh" ]; then
  "$DOTFILES_DIR/scripts/preflight.sh" || true
else
  skip "scripts/preflight.sh not present — skipping verification"
fi
